# Generated by Django 3.0 on 2020-09-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_voter', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('branch', models.CharField(choices=[('it', 'IT'), ('cse', 'CSE'), ('civil', 'CIVIL'), ('eee', 'EEE'), ('ece', 'ECE'), ('chemical', 'CHEMICAL'), ('biotech', 'BIOTECH'), ('mech', 'MECH'), ('prod', 'PROD')], default='cse', max_length=8)),
                ('year', models.CharField(choices=[('1st', '1ST'), ('2nd', '2ND'), ('3rd', '3RD'), ('4th', '4TH')], default='1st', max_length=6)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=130)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
