# Generated by Django 3.0 on 2020-09-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='candidate',
            new_name='user',
        ),
    ]
